package org.example.hrms.mernisReferance;

//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 8.0.1.1
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: 493FEFFC38E859D060885E45E90BCD4A99BC4544DBEC4A426BA58816FD90A524623E38B48B6FCC4A518CB7DCD5CD259EBF2C9D4F5CDD7ECECC6BB8508EBC752B
//------------------------------------------------------------------------
import java.util.Date;


public interface DAVDateTimeConverter
{
    java.util.Date convertDateTime(String strDate);
    java.util.Date convertTime(String strDate);
    java.util.Date convertDate(String strDate);
    String convertDuration(String value);
    String getStringFromDateTime(Date value);
    String getStringFromDate(Date value);
    String getStringFromTime(Date value);
    String getStringFromDuration(String value);
}